# Python review

Goals:
- recall basic Python vocabulary
- Practice markdown

## Libraries and Packages

**library**: A collection of code that we can use to perform specifc tasks in our programs.

**Numpy**: 
- core library for numerical computing in Pythin
- many other libraries use Numpy arrays as building blocks
- computions on NumPy are optiomized for speed and memory usage

In [2]:
import numpy as np

In [4]:
# Assign a small array to a variable a
a = np.array([[1,1,2], [3,5,8]])

In [5]:
# Run cell with the variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [6]:
# Use `print`function to print value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

*object** (informaly speaking) is a bundle of proporties and actions about something specific.
Example:
Object: data frame
Properties: Number rows, names of the columns, date created
Actions: selecting a specifc row, adding a new column
A variable id the name we give a specific object, and the same object can be referenced by different variable.
In practice, we can often use variables and objects interchangeably
