# Python review

Goals:
- recall basic Python vocabulary
- Practice markdown

## Libraries and Packages

**library**: A collection of code that we can use to perform specifc tasks in our programs.

**Numpy**: 
- core library for numerical computing in Pythin
- many other libraries use Numpy arrays as building blocks
- computions on NumPy are optiomized for speed and memory usage

In [1]:
import numpy as np

In [2]:
# Assign a small array to a variable a
a = np.array([[1,1,2], [3,5,8]])

In [3]:
# Run cell with the variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Use `print`function to print value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

*object** (informaly speaking) is a bundle of proporties and actions about something specific.
Example:
Object: data frame
Properties: Number rows, names of the columns, date created
Actions: selecting a specifc row, adding a new column
A variable id the name we give a specific object, and the same object can be referenced by different variable.
In practice, we can often use variables and objects interchangeably


In [5]:
# Check the type/class of a variable/object by using `type`function



In [6]:
# Check the type on an entry on the array by indexing
type(a[0,0])

numpy.int64

This information is a **docstring**

A function has two types of arguments:

- ** non-optional argumet**: arguments *you* need to specify for the function to so something
- **optional argument**: arguments that are pre-filled with a defauld value by the function



## Atributes & methods 

An object in Python has attibutes.

-**attribute**: a property of an object, some piece of information about it
-**method**: a procedure associated with the object, an action where the main ingredient is the object.

## Check-in

Fish attributes:

-length, color, species
-die(), bite(), swim()

**Examples**
Attributes for `numpy.arrays`

We can access a variable's and methods by adding a period `.`at the end of the variable's name.

`variable.method()` or `variable.attribute`


In [7]:
a.shape

(2, 3)

In [8]:
type(a.shape)

tuple

In [9]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [10]:
# Methods examples
# min() returns the minimum value along a specific axis
a.min(axis=0)

array([1, 1, 2])

## Check-in

We can also call the `min`method without any parameters:

In [11]:
a.min()

1

Remember: methods are functions associated with an object

In [12]:
type(a.min)

builtin_function_or_method

## Exercise

1 Read the `print`function help. What is the type of the argument `sep`? Is this an optional or non optional argument? Why?

2 Create two new variables one with the integer value 77 and another one with the string 99.

3 Use your variables to print `77%99%77 by changing the value of one of the optional argumets in `print`

In [15]:
?print

In [16]:
x = 77
y ='99'
print(x,y,x, sep='%')

77%99%77
